apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.ai.example.com
  labels:
    app.kubernetes.io/name: kubeagentic
    app.kubernetes.io/component: crd
spec:
  group: ai.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - provider
            - model
            - systemPrompt
            - apiSecretRef
            properties:
              provider:
                type: string
                enum:
                - "openai"
                - "gemini"
                - "claude"
                - "vllm"
                description: "LLM provider to use for this agent"
              model:
                type: string
                description: "Specific model to use (e.g., gpt-4, gemini-pro, claude-3)"
              systemPrompt:
                type: string
                description: "System prompt that defines the agent's persona and behavior"
              apiSecretRef:
                type: object
                required:
                - name
                - key
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes Secret containing API credentials"
                  key:
                    type: string
                    description: "Key within the secret containing the API key"
                description: "Reference to secret containing LLM provider API credentials"
              endpoint:
                type: string
                description: "Custom endpoint URL for self-hosted models (optional)"
              tools:
                type: array
                items:
                  type: object
                  required:
                  - name
                  - description
                  properties:
                    name:
                      type: string
                      description: "Tool identifier"
                    description:
                      type: string
                      description: "Human-readable description of what this tool does"
                    inputSchema:
                      type: object
                      description: "JSON schema describing the tool's input parameters"
                      x-kubernetes-preserve-unknown-fields: true
                description: "Array of tools available to the agent"
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                default: 1
                description: "Number of agent pod replicas to run"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      memory:
                        type: string
                        default: "256Mi"
                      cpu:
                        type: string
                        default: "100m"
                  limits:
                    type: object
                    properties:
                      memory:
                        type: string
                        default: "512Mi"
                      cpu:
                        type: string
                        default: "200m"
                description: "Resource requests and limits for agent pods"
              serviceType:
                type: string
                enum:
                - "ClusterIP"
                - "NodePort"
                - "LoadBalancer"
                default: "ClusterIP"
                description: "Kubernetes service type for agent endpoint"
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - "Pending"
                - "Running" 
                - "Failed"
                - "Succeeded"
                description: "Current phase of the agent deployment"
              message:
                type: string
                description: "Human-readable message about the current state"
              replicaStatus:
                type: object
                properties:
                  ready:
                    type: integer
                    description: "Number of ready replicas"
                  desired:
                    type: integer
                    description: "Number of desired replicas"
                  available:
                    type: integer
                    description: "Number of available replicas"
              lastUpdated:
                type: string
                format: date-time
                description: "Timestamp of last status update"
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - "Unknown"
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
    additionalPrinterColumns:
    - name: Provider
      type: string
      jsonPath: .spec.provider
    - name: Model
      type: string
      jsonPath: .spec.model
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Ready
      type: string
      jsonPath: .status.replicaStatus.ready
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: agents
    singular: agent
    kind: Agent
    shortNames:
    - ag

