# KubeAgentic Website Configuration
title: KubeAgentic
description: Deploy and manage AI agents on Kubernetes with simple YAML configurations
baseurl: ""
url: "https://kubeagentic.com"

# SEO and Social
author: KubeAgentic Team
email: contact@kubeagentic.com
twitter:
  username: kubeagentic
  card: summary_large_image
github:
  username: KubeAgentic-Community
  repository_url: https://github.com/KubeAgentic-Community/KubeAgentic

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Tag settings
seo:
  type: "WebSite"
  name: "KubeAgentic"
  description: "Deploy and manage AI agents on Kubernetes with simple YAML configurations"
  url: "https://kubeagentic.com"
  image: "https://kubeagentic.com/assets/logo.png"
  twitter:
    card: "summary_large_image"
    site: "@kubeagentic"

# Navigation
header_pages:
  - index.md
  - direct-framework.md
  - langgraph-framework.md
  - yaml-generator.md
  - api-reference.md
  - examples.md
  - local-testing.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "page"

# GitHub Pages settings
repository: KubeAgentic-Community/KubeAgentic

# Social links
github_username: KubeAgentic-Community

# Exclude from processing
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - webpack.config.js
  - "*.go"
  - go.mod
  - go.sum
  - Dockerfile*
  - Makefile
  - .git/
  - .gitignore
  - bin/
  - scripts/
