apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeagentic-operator
  namespace: kubeagentic-system
  labels:
    app.kubernetes.io/name: kubeagentic
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeagentic
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeagentic
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: kubeagentic-operator
      containers:
      - name: operator
        image: sudeshmu/kubeagentic:operator-latest
        imagePullPolicy: Always
        args:
        - --leader-elect
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        env:
        - name: AGENT_IMAGE
          value: "kubeagentic/agent:latest"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 9443
          name: webhook
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10