apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeagentic-operator
  namespace: kubeagentic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeagentic-operator-role
rules:
- apiGroups:
  - ai.example.com
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.example.com
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - ai.example.com
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeagentic-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeagentic-operator-role
subjects:
- kind: ServiceAccount
  name: kubeagentic-operator
  namespace: kubeagentic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeagentic-operator-leader-election
  namespace: kubeagentic-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeagentic-operator-leader-election
  namespace: kubeagentic-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeagentic-operator-leader-election
subjects:
- kind: ServiceAccount
  name: kubeagentic-operator
  namespace: kubeagentic-system