apiVersion: ai.example.com/v1
kind: Agent
metadata:
  name: customer-support-agent
  namespace: default
spec:
  provider: "openai"
  model: "gpt-4"
  systemPrompt: |
    You are a helpful customer support agent for an e-commerce company.
    You should be friendly, professional, and always try to resolve customer issues.
    If you cannot resolve an issue, escalate it to a human agent.
    Always ask for order numbers when dealing with order-related issues.
  apiSecretRef:
    name: openai-secret
    key: api-key
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  serviceType: "ClusterIP"
  tools:
  - name: "order_lookup"
    description: "Look up order information by order ID"
    inputSchema:
      type: "object"
      properties:
        order_id:
          type: "string"
          description: "The order ID to look up"
      required: ["order_id"]
  - name: "inventory_check"
    description: "Check if a product is in stock"
    inputSchema:
      type: "object"
      properties:
        product_id:
          type: "string"
          description: "The product ID to check"
      required: ["product_id"]
---
# Secret containing OpenAI API key
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: default
type: Opaque
data:
  # Replace with base64 encoded OpenAI API key
  # echo -n "your-openai-api-key" | base64
  api-key: "eW91ci1vcGVuYWktYXBpLWtleQ=="